### ISSUE TITLE
Cannot specify token expiry for `GetIDTokenFromServiceAccount`

### ISSUE THREAD

**Issue by QaisarRajput** [salrashid123/salrashid123.github.io#1]
I am trying to specify token expiry time (which is 1 hour as default), within `GetIDTokenFromServiceAccount` function. There is parameter named `additional_claims`, which can take the `jwt` payload parameters. see the following.

        def GetIDTokenFromServiceAccount(svcAccountFile, target_audience, payload):
               creds = service_account.IDTokenCredentials.from_service_account_file(svcAccountFile,target_audience = target_audience, additional_claims = payload)
  
               request = google.auth.transport.requests.Request()
               creds.refresh(request)
               return creds.token
       
        def VerifyIDToken(token, certs_url,  audience=None):
               request = google.auth.transport.requests.Request()
               result = id_token.verify_token(token,
                                  request,
                                  certs_url = certs_url)
               print(result) <<======
               if audience in result['aud']:
                     return True
               return False

Here i generate the token using the custom expiry time for the token
        
        TOKEN_LIFETIME_SECS = 1200
        now = _helpers.utcnow()
        lifetime = datetime.timedelta(seconds = TOKEN_LIFETIME_SECS)
        expiry = now + lifetime
        payload = {
            "iat": _helpers.datetime_to_secs(now),
            "exp": _helpers.datetime_to_secs(expiry)
        }

        # For ServiceAccount
        token = GetIDTokenFromServiceAccount(svcAccountFile, target_audience, payload)
            
        print('Token: ' + token)
        
        if VerifyIDToken(token, certs_url, target_audience):
            print ('Token Verified with aud: ' + target_audience)
            print ('Making Authenticated API call:')
            MakeAuthenticatedRequest(token,url)

Above code generates the token. But when i verify the token, where internally it decodes the token information, i print that information (see the `<<====` in the `VerifyIDToken` Function). It still shows the parameters `iat` and `exp` which are 1 hour apart.

Please suggest how can this custom token expiry can be set

**Comment by salrashid123** [comment]
I think the OIDC token issued by google is always set to an hour (the `id_token` you get back in response from google, that is).  

fyi- the bit here sets the expiry for JWT  that is sent _to_ google (not the `id_token` you get back _from_ google
https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/service_account.py#L496

btw, the `custom_claims` bit is pretty much ignored anyway AFAIK...i'm trying to remove it in compute credentials as well:
https://github.com/googleapis/google-auth-library-python/pull/362

**Comment by QaisarRajput** [comment]
> fyi- the bit here sets the expiry for JWT that is sent _to_ google (not the `id_token` you get back _from_ google
> https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/service_account.py#L496

I actually went through this to implement the expiry logic. So you mean as of now there is no way to change the expiration time? Please suggest if you think there is something worth looking at

**Comment by salrashid123** [comment]
No, thats the token you sent over _to_ google's token endpoint.  The token endpoint will reply back w/ the id_token you requested which is signed by google (the expiration time in the response is 3600s and is not related to the first `exp` you send over.  If you're interested in the raw flow, see the golang snippet here:

https://github.com/salrashid123/google_id_token/blob/master/golang/GoogleIDToken.go#L46
